
version: "2"
networks:
  network_practica:
volumes:
  prometheus.yml:
  myGrafanaVol:
  datasources.yml:
services:
  app:
    build: .
    container_name: myapp_practica
    ports:
      - "83:3000"
    networks:
      - "network_practica"
  prometheus: 
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    depends_on:
      - app
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - "network_practica"
  grafana:
    image:  grafana/grafana:7.1.5
    container_name: grafana_practica
    depends_on:
      - prometheus
    volumes:
      - myGrafanaVol:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1
    ports:
      - "3500:3000"
    networks:
      - "network_practica"